CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, full_name text NOT NULL DEFAULT '', national_id text NOT NULL DEFAULT '', mobile text NOT NULL DEFAULT '', theme text NOT NULL DEFAULT 'dark');
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own profile" ON public.profiles FOR ALL TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE TABLE public.letters (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, preview jsonb NOT NULL, content jsonb NOT NULL, unlocked boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT (id, user_id, preview, unlocked, created_at), DELETE ON public.letters TO authenticated;
GRANT ALL ON public.letters TO service_role;
ALTER TABLE public.letters ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own letter previews" ON public.letters FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Delete own letters" ON public.letters FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE public.conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, title text NOT NULL, messages jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.conversations TO authenticated;
GRANT ALL ON public.conversations TO service_role;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own conversations" ON public.conversations FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE TABLE public.payment_redemptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, order_id text UNIQUE NOT NULL, letter_id uuid REFERENCES public.letters(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.payment_redemptions TO authenticated;
GRANT ALL ON public.payment_redemptions TO service_role;
ALTER TABLE public.payment_redemptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own receipts" ON public.payment_redemptions FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE TABLE public.memberships (user_id uuid PRIMARY KEY, expires_at timestamptz NOT NULL);
GRANT SELECT ON public.memberships TO authenticated;
GRANT ALL ON public.memberships TO service_role;
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own membership" ON public.memberships FOR SELECT TO authenticated USING (auth.uid() = user_id);